//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecreteMap
    {
        public int UserId { get; set; }
        public int SecreteQuestionId { get; set; }
        public string Answer { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
    
        public virtual SCUser SCUser { get; set; }
        public virtual SecreteQuestionMaster SecreteQuestionMaster { get; set; }
    }
}
